name: fetch-daily-prices

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: get current date and hour and save it as environment variable
        run: echo "NOW::$(date +'%Y%m%d%H')" >> $GITHUB_ENV
          
      - name: execute fetch script
        run: python fetch_data_from_request.py
        
      - name: execute clean script
        run: python clean_fetched_data.py raw_data/raw-$NOW

      - name: commit files
        run: |
          git config --local user.email "chinmay.kunkikar@gmail.com"
          git config --local user.name "Chinmay Kunkikar (GitHub Action)"
          git add -A
          git commit -m "Fetch jiomart prices ($(date +'%d-%m-%Y'))" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
